name: Security Vulnerability (Low Severity)
description: Report a low-severity security vulnerability in NSS
title: "[Security]: "
labels: ["security", "priority: low"]
assignees:
  - LEEI1337
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** This template is for **LOW severity** vulnerabilities only.

        For **Critical** or **High** severity vulnerabilities, please report them via email to **security@nss-standard.eu**. Do NOT create a public issue for critical or high severity vulnerabilities.

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the vulnerability.
      placeholder: Describe the vulnerability...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: The severity of the vulnerability (this template is for LOW severity only).
      options:
        - Low
        - Informational
    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: Affected Component
      description: Which NSS component is affected?
      options:
        - Cognitive Gateway (Layer 3)
        - Agent Execution (Layer 2)
        - Knowledge Fabric (Layer 1)
        - Guardian Shield (Layer 4)
        - Governance Plane (Layer 5)
        - MARS
        - APEX
        - SENTINEL
        - SHIELD
        - VIGIL
        - PII Redaction
        - STEER Routing
        - DPSparseVoteRAG
        - API Gateway
        - Configuration
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the vulnerability.
      placeholder: |
        1. Configure ...
        2. Send request ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that may help assess this vulnerability.
    validations:
      required: false
